version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: leany
      POSTGRES_PASSWORD: leany123
      POSTGRES_DB: leanydb
    ports:
      - '5433:5432'
    volumes:
      - leany_pgdata:/var/lib/postgresql/data

volumes:
  leany_pgdata:
